### ISSUE TITLE
Est-il possible de simuler une bougie ?

### ISSUE THREAD

**Issue by houpdelta** [Bbillyben/ColorTransition#14]
Comment dans un scenario Jeedom faire que la lampe en continue vacille en rouge / orange ?

**Comment by Bbillyben** [comment]
Salut houpdelta, 

Il y a l'info "status" que tu peux suivre dans un scénario pour relancer l'animation dans le sens inverse.
mais Une bougie ça scintille rapidement et aléatoirement, pas sur que ça rende bien par une transition douce, même rapide, et sans aléatoire.
